/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author svv
 */
public class New_Student extends javax.swing.JFrame {

    /**
     * Creates new form New_Student
     */
    public New_Student() {
        initComponents();
        s1.setSelected(true);
        s1.setEnabled(false);
        s2.setSelected(true);
        s2.setEnabled(false);
        s3.setSelected(true);
        s3.setEnabled(false);
        
    }
    public void get(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        RollTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        s = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddrTA = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PhTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        s1 = new javax.swing.JCheckBox();
        s2 = new javax.swing.JCheckBox();
        s3 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        s41 = new javax.swing.JRadioButton();
        s51 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        s52 = new javax.swing.JRadioButton();
        s42 = new javax.swing.JRadioButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        g2 = new javax.swing.JRadioButton();
        g1 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Roll No.:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 11, -1, 28));

        RollTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RollTF.setOpaque(false);
        RollTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RollTFKeyTyped(evt);
            }
        });
        getContentPane().add(RollTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 15, 240, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name.:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 45, -1, 28));

        NameTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameTF.setOpaque(false);
        getContentPane().add(NameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 49, 240, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Class.:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 79, -1, 28));

        c.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XI", "XII" }));
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 83, 240, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Section.:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 113, -1, 28));

        s.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B" }));
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 117, 240, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Gender.:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 147, 68, 28));

        AddrTA.setColumns(20);
        AddrTA.setRows(5);
        jScrollPane1.setViewportView(AddrTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 193, 240, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Address.:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 193, -1, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Phone No.:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 329, -1, 28));

        PhTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PhTF.setOpaque(false);
        PhTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhTFKeyTyped(evt);
            }
        });
        getContentPane().add(PhTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 333, 240, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Subject.:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 363, -1, 28));

        s1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("Chemistry");
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 392, -1, 32));

        s2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setText("Physics");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        getContentPane().add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 366, -1, -1));

        s3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setText("English");
        getContentPane().add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 426, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Subject 2.:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 88, 28));

        buttonGroup2.add(s41);
        s41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s41.setForeground(new java.awt.Color(255, 255, 255));
        s41.setText("Maths");
        getContentPane().add(s41, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 453, -1, -1));

        buttonGroup3.add(s51);
        s51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s51.setForeground(new java.awt.Color(255, 255, 255));
        s51.setText("I.P");
        getContentPane().add(s51, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 487, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Subject 3.:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 484, 88, 28));

        buttonGroup3.add(s52);
        s52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s52.setForeground(new java.awt.Color(255, 255, 255));
        s52.setText("P.E");
        getContentPane().add(s52, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 487, -1, -1));

        buttonGroup2.add(s42);
        s42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s42.setForeground(new java.awt.Color(255, 255, 255));
        s42.setText("Biology");
        getContentPane().add(s42, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 453, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/back.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(255, 520, 117, 50);
        jDesktopPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/update.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(125, 520, 107, 50);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Add.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(8, 520, 109, 50);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(g2);
        g2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        g2.setForeground(new java.awt.Color(255, 255, 255));
        g2.setText("Female");
        g2.setBounds(240, 150, 90, 25);
        jDesktopPane1.add(g2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(g1);
        g1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        g1.setForeground(new java.awt.Color(255, 255, 255));
        g1.setText("Male");
        g1.setBounds(140, 150, 80, 25);
        jDesktopPane1.add(g1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 590));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-391)/2, (screenSize.height-638)/2, 391, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RollTF.setText("");
        NameTF.setText("");
        AddrTA.setText("");
        PhTF.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ro = Integer.parseInt(RollTF.getText());
        String nam = NameTF.getText();
        String add = AddrTA.getText();
        String ph = PhTF.getText();              
        String cls = (String) c.getSelectedItem();
        String sect = (String) s.getSelectedItem();
        String gen = null;
        if (g1.isSelected())
        {
            gen = "Male";
        }
        if (g2.isSelected()) {
            gen = "Female";
        }
        String sub1="Chemistry";
        String sub2="Physics";
        String sub3="Englsh";
        String sub4 = null;
        if(s41.isSelected())
        {
            sub4="Maths";
        }
        if(s42.isSelected())
        {
            sub4="Biology";
        }
        String sub5 = null;
        if(s51.isSelected())
        {
            sub5="IP";
        }
        if(s52.isSelected())
        {
            sub5="PE";
        }
        
        try
        {   
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sms", "root", "mysql");
            PreparedStatement ps = (PreparedStatement) conn.prepareStatement(" insert into student(roll_no,Name,Class,Section,Gender,Address,Phone_No,s1,s2,s3,s4,s5) values(?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setInt(1, ro);            
            ps.setString(2, nam);
            ps.setString(3, cls);
            ps.setString(4, sect);
            ps.setString(5, gen);
            ps.setString(6, add);
            ps.setString(7, ph);
            ps.setString(8, sub1);
            ps.setString(9, sub2);
            ps.setString(10, sub3);
            ps.setString(11, sub4);
            ps.setString(12, sub5);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data successfully Saved!");
            ps.close();
            conn.close(); 
        }
        catch (SQLException | ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Database Connectivity Error!! Please Check Connection" + ex);
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Admin ob = new Admin();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void RollTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RollTFKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_RollTFKeyTyped

    private void PhTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhTFKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_PhTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new New_Student().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddrTA;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField PhTF;
    private javax.swing.JTextField RollTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox c;
    private javax.swing.JRadioButton g1;
    private javax.swing.JRadioButton g2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox s;
    private javax.swing.JCheckBox s1;
    private javax.swing.JCheckBox s2;
    private javax.swing.JCheckBox s3;
    private javax.swing.JRadioButton s41;
    private javax.swing.JRadioButton s42;
    private javax.swing.JRadioButton s51;
    private javax.swing.JRadioButton s52;
    // End of variables declaration//GEN-END:variables
}
