/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author svv
 */
public class Remove_student extends javax.swing.JFrame {

    /**
     * Creates new form Remove_student
     */
    public Remove_student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cls = new javax.swing.JComboBox();
        section = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rol = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Class: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        cls.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cls.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11", "12" }));
        getContentPane().add(cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 11, 122, -1));

        section.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        section.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E" }));
        getContentPane().add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 45, 122, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Section: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Roll No.:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        rol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rolKeyTyped(evt);
            }
        });
        getContentPane().add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 79, 122, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/delete.png"))); // NOI18N
        jButton1.setText("Remove Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 209, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(10, 190, 209, 50);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 510, 430));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-245)/2, (screenSize.height-274)/2, 245, 274);
    }// </editor-fold>//GEN-END:initComponents
    java.sql.Statement stmt = null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if( "".equals(rol.getText()))
    {
        JOptionPane.showMessageDialog(this, "Please fill all the details.");
    }
    else
    {
        String clas = (String) cls.getSelectedItem();  
        String sect = (String) section.getSelectedItem();  
        int ro = Integer.parseInt(rol.getText());
       
        try 
        {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/sms", "root", "mysql");
            stmt = conn.createStatement();
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////
            String strSQL = ("delete  from fa1 where Roll ='"+(ro)+"' and Class ='"+(clas)+"' and Sec ='"+(sect)+"';");
            int rowsEffected = stmt.executeUpdate(strSQL);
            if (rowsEffected == 0)
            {
                JOptionPane.showMessageDialog(this, " FA-1 Record does not exists");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Record Deleted");
            }
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////
            String strSQL1 = ("delete  from fa2 where Roll ='"+(ro)+"' and Class ='"+(clas)+"' and Sec ='"+(sect)+"';");
            int rowsEffected1 = stmt.executeUpdate(strSQL1);
            if (rowsEffected1 == 0)
            {
                JOptionPane.showMessageDialog(this, " FA-2 Record does not exists");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Record Deleted");
            }
            /////////////////////////////////////////////////////////////////////////////////////////////////////////////
            String strSQL2 = ("delete  from fa3 where Roll ='"+(ro)+"' and Class ='"+(clas)+"' and Sec ='"+(sect)+"';");
            int rowsEffected2 = stmt.executeUpdate(strSQL2);
            if (rowsEffected2 == 0)
            {
                JOptionPane.showMessageDialog(this, " FA-3 Record does not exists");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Record Deleted");
            }
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////
            String strSQL3 = ("delete  from fa4 where Roll ='"+(ro)+"' and Class ='"+(clas)+"' and Sec ='"+(sect)+"';");
            int rowsEffected3 = stmt.executeUpdate(strSQL3);
            if (rowsEffected3 == 0)
            {
                JOptionPane.showMessageDialog(this, " FA-4 Record does not exists");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Record Deleted");
            }
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////
            String strSQL4 = ("delete  from sa1 where Roll ='"+(ro)+"' and Class ='"+(clas)+"' and Sec ='"+(sect)+"';");
            int rowsEffected4 = stmt.executeUpdate(strSQL4);
            if (rowsEffected4 == 0)
            {
                JOptionPane.showMessageDialog(this, " SA-1 Record does not exists");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Record Deleted");
            }
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////
            String strSQL5 = ("delete  from sa2 where Roll ='"+(ro)+"' and Class ='"+(clas)+"' and Sec ='"+(sect)+"';");
            int rowsEffected5 = stmt.executeUpdate(strSQL5);
            if (rowsEffected5 == 0)
            {
                JOptionPane.showMessageDialog(this, " SA-2 Record does not exists");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Record Deleted");
            }
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////
            String strSQL6 = ("delete  from student where roll_no ='"+(ro)+"' and Class ='"+(clas)+"' and Section ='"+(sect)+"';");
            int rowsEffected6 = stmt.executeUpdate(strSQL6);
            if (rowsEffected6 == 0)
            {
                JOptionPane.showMessageDialog(this, " Student Record does not exists");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Record Deleted");
            }
        }
        catch (SQLException | ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Database Connectivity Error!! Please Check Connection" + ex);
        } 
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rolKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_rolKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Remove_student().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cls;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField rol;
    private javax.swing.JComboBox section;
    // End of variables declaration//GEN-END:variables
}
